// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const fs = require('fs');
const path = require('path');

const docsDir = path.join(__dirname, 'docs');

// Helper to create a sidebar item from a directory, using _category_.json if present
/**
 * @param {string} dirName
 * @returns {any}
 */
function getSidebarItemForDir(dirName) {
  const categoryPath = path.join(docsDir, dirName, '_category_.json');
  /** @type {any} */
  let categoryConfig = {};
  if (fs.existsSync(categoryPath)) {
    try {
      categoryConfig = JSON.parse(fs.readFileSync(categoryPath, 'utf8'));
    } catch (e) {
      console.error(`Error parsing ${categoryPath}`, e);
    }
  }

  // If _category_.json exists, use it to create a category item
  if (categoryConfig.label) {
    const item = {
      type: 'category',
      label: categoryConfig.label,
      link: categoryConfig.link,
      items: [{ type: 'autogenerated', dirName: dirName }],
      collapsed: true,
    };
    // Add className if specified (for dividers)
    if (categoryConfig.className) {
      item.className = categoryConfig.className;
    }
    return item;
  }
  
  // Fallback to autogenerated (flattened) if no category config found
  return { type: 'autogenerated', dirName: dirName };
}

// Define exact sidebar order
/** @type {any[]} */
const tutorialSidebar = [
  // 1. Blender for Visual Investigation (intro doc)
  { type: 'doc', id: 'intro' },
  
  // 2. Introduction
  getSidebarItemForDir('introduction'),
  
  // 3. 3D
  getSidebarItemForDir('3D'),
  
  // 4. Modeling
  getSidebarItemForDir('modeling'),
  
  // 5. Data
  getSidebarItemForDir('data'),
  
  // 6. Blender
  getSidebarItemForDir('blender'),
  
  // 7. Tools, Add-ons & Techniques
  getSidebarItemForDir('tools-addons-techniques'),
  
  // 8. Use Cases & Tutorials
  getSidebarItemForDir('use-cases'),
  
  // --- Divider (via CSS class on template-pages) ---
  
  // 9. Template Pages
  getSidebarItemForDir('template-pages'),
  
  // 10. Archive
  getSidebarItemForDir('archive'),
];

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar,
};

module.exports = sidebars;