// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const fs = require('fs');
const path = require('path');

// Build sidebar by autogenerating one entry per top-level docs folder,
// then append a divider and the template-pages + archive folders at the end.
const docsDir = path.join(__dirname, 'docs');
const dirents = fs.readdirSync(docsDir, { withFileTypes: true });
const topLevelDirs = dirents
  .filter((/** @type {import('fs').Dirent} */ d) => d.isDirectory())
  .map((/** @type {import('fs').Dirent} */ d) => d.name)
  // Exclude special folders we'll append later
  .filter(n => n !== 'template-pages' && n !== 'archive');

// Keep alphabetical order by default, but move `data` to just before `use cases`
topLevelDirs.sort();
const dataIndex = topLevelDirs.indexOf('module-2-data');
const useCasesIndex = topLevelDirs.indexOf('module-4-use-cases');
if (dataIndex !== -1 && useCasesIndex !== -1) {
  topLevelDirs.splice(dataIndex, 1);
  topLevelDirs.splice(useCasesIndex, 0, 'module-2-data');
}

// Helper to create a sidebar item from a directory, using _category_.json if present
/**
 * @param {string} dirName
 * @returns {any}
 */
function getSidebarItemForDir(dirName) {
  const categoryPath = path.join(docsDir, dirName, '_category_.json');
  /** @type {any} */
  let categoryConfig = {};
  if (fs.existsSync(categoryPath)) {
    try {
      categoryConfig = JSON.parse(fs.readFileSync(categoryPath, 'utf8'));
    } catch (e) {
      console.error(`Error parsing ${categoryPath}`, e);
    }
  }

  // If _category_.json exists, use it to create a category item
  if (categoryConfig.label) {
    return {
      type: 'category',
      label: categoryConfig.label,
      link: categoryConfig.link,
      items: [{ type: 'autogenerated', dirName: dirName }],
      collapsed: true,
    };
  }
  
  // Fallback to autogenerated (flattened) if no category config found
  return { type: 'autogenerated', dirName: dirName };
}

/** @type {any[]} */
const tutorialSidebar = topLevelDirs.map(getSidebarItemForDir);

// Add the intro doc to the beginning of the sidebar
tutorialSidebar.unshift({ type: 'doc', id: 'intro' });

// Insert a visual divider, then template-pages and archive (archive should be last)

tutorialSidebar.push(getSidebarItemForDir('template-pages'));
tutorialSidebar.push(getSidebarItemForDir('archive'));

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar,
};

module.exports = sidebars;